SRC_LINK = ../../

INC = -I./include
INC += -I../../

test:
	c++ -o test_Gizmo tests/Gizmo_test.cpp Gizmo.cpp $(SRC_LINK)actors/Actor.cpp $(SRC_LINK)map/MapData.cpp $(SRC_LINK)map/Tile.cpp $(INC) -std=c++11
