variables:
	PROJECT_NAME: "ProjectX - Capture The Flag"

#Begin testing text
before_script:
	- echo "Starting testing for $PROJECT_NAME"

#List of testing stages
stages:
	- build

# Try to compile file
build:
  stage: build
  tags:
    - ubuntu16.04
  script:
    - echo "Starting build testing:"
    - make
